### ISSUE TITLE
Filename hook (custom file name index-)

### ISSUE THREAD

**Issue by enricodeleo** [poweredcache/powered-cache#140]
I'm struggling with the implementation of a web server-level serving mechanism. I already implemented in nginx a configuration that serves public pages (e.g. index-ssl.html) but I'd like to do the same for logged in users too.
Problem is the filename is not just `-username` but it also append the timestamp. How can we force powered cache dropping the timestamp part?

I'd love a filter on `powered_cache_index_file` function so that we can change the string.

Is this possible?

thanks!

**Comment by mustafauysal** [comment]
Hi @enricodeleo,

> I already implemented in nginx a configuration that serves public pages (e.g. index-ssl.html) but I'd like to do the same for logged in users too.

It's not a good idea to implement the same logic for logged-in users. 

> Problem is the filename is not just -username but it also append the timestamp. How can we force powered cache dropping the timestamp part?

It's not a timestamp; it's a hash designed to prevent direct cache hits. This was specifically implemented to avoid direct cache hits without executing PHP.

> I'd love a filter on powered_cache_index_file function so that we can change the string.

It's not possible because drop-ins are loaded before WP loads the plugin API. So, it's not possible to use do_actions/apply_filters early stage of bootstrapping WP. 


I hope this helps.

**Comment by mustafauysal** [comment]
@enricodeleo I'm closing this issue for now. Feel free to reopen it if you have any more questions.
